
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jul 18 20:37:50 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 51;
  public static final int LBRACKET = 10;
  public static final int CONST = 7;
  public static final int GRT = 24;
  public static final int NAMESP = 5;
  public static final int NOT_EQUAL = 23;
  public static final int CONTINUE = 45;
  public static final int LPAREN = 16;
  public static final int SEMI = 8;
  public static final int NUM_CONST = 49;
  public static final int FOR = 40;
  public static final int LESS = 26;
  public static final int MINUS = 31;
  public static final int STATIC = 14;
  public static final int RPAREN = 17;
  public static final int AND = 37;
  public static final int RANGE = 39;
  public static final int IN = 41;
  public static final int OR = 36;
  public static final int COMMA = 6;
  public static final int CLASS = 12;
  public static final int INC = 20;
  public static final int DIV = 33;
  public static final int GRT_EQUAL = 25;
  public static final int LESS_EQUAL = 27;
  public static final int PLUS = 30;
  public static final int IF = 42;
  public static final int ASSIGN = 9;
  public static final int DOT = 35;
  public static final int EOF = 0;
  public static final int RETURN = 46;
  public static final int RESOLUTION = 19;
  public static final int RBRACKET = 11;
  public static final int EQUAL = 22;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int MUL = 32;
  public static final int MOD = 34;
  public static final int IDENT = 48;
  public static final int BREAK = 44;
  public static final int VOID = 18;
  public static final int ARROW = 29;
  public static final int COLON = 15;
  public static final int ELSE = 43;
  public static final int LBRACE = 3;
  public static final int READ = 47;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 50;
  public static final int DEC = 21;
  public static final int PRINT = 28;
}

